# Objective

### Analyze sales data using SQL by applying Subqueries, CTEs, and Window Functions to solve business queries. Steps: Load Superstore dataset into a table (superstore_raw). Create tables (customers, orders, products) from the dataset. Insert data into these tables using SELECT DISTINCT. Apply subqueries to filter data (above average sales, highest order per customer). Use CTEs to compute aggregations (total sales per customer). Apply window functions (ROW_NUMBER, RANK) for ranking and analysis. Combine JOIN + CTE + Window Functions for final result (customer, total sales, rank). Solve business queries (top customers, low customers, single-order customers, above-average sales). Output: SQL script / Notebook + query results + brief insights.

##### Cell 1: Import Libraries

In [1]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine
from urllib.parse import quote_plus

##### Cell 2: Connect to MySQL

In [2]:
password = quote_plus("Saritamanas@123")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost/superstore_db"
)

print("Connected Successfully")

Connected Successfully

##### Cell 3: Verify Data

In [3]:
query = "SELECT * FROM superstore_raw LIMIT 5;"
pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

#### Step 1: Setup Data 

#### Import the Superstore dataset into a table named superstore_raw. 

#### Create these 3 tables from it:  

#### customers  

#### orders  

#### products  

#### Insert data into these tables using SELECT DISTINCT.

##### Cell 4: Customers Table

In [4]:
query = """
CREATE TABLE IF NOT EXISTS customers AS
SELECT DISTINCT
`Customer ID`,
`Customer Name`,
Segment,
City,
State,
Region
FROM superstore_raw;
"""

with engine.begin() as conn:
    conn.exec_driver_sql(query)

print("Customers Table Created")

Customers Table Created

##### Cell 5: Products Table

In [5]:
query = """
CREATE TABLE IF NOT EXISTS products AS
SELECT DISTINCT
`Product ID`,
`Product Name`,
Category,
`Sub-Category`
FROM superstore_raw;
"""

with engine.begin() as conn:
    conn.exec_driver_sql(query)

print("Products table created")

Products table created

##### Cell 6: Orders Table

In [6]:
query = """
CREATE TABLE IF NOT EXISTS orders AS
SELECT DISTINCT
`Order ID`,
`Order Date`,
`Customer ID`,
Sales,
Quantity,
Discount,
Profit
FROM superstore_raw;
"""

with engine.begin() as conn:
    conn.exec_driver_sql(query)

print("Orders table created")

Orders table created

### Step 2: Perform Required Queries

#### Write and execute SQL queries for each of the following:

##### 1. Find all orders where sales are greater than the average sales. (Subquery)

In [7]:
query = """
SELECT *
FROM orders
WHERE Sales >
(
SELECT AVG(Sales)
FROM orders
);
"""

pd.read_sql(query, engine)

,Order ID,Order Date,Customer ID,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,CG-12520,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,CG-12520,731.9400,3,0.00,219.5820
2,US-2015-108966,2015-10-11,SO-20335,957.5775,5,0.45,-383.0310
3,CA-2014-115812,2014-06-09,BH-11710,907.1520,6,0.20,90.7152
4,CA-2014-115812,2014-06-09,BH-11710,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...
2354,US-2016-103674,2016-12-06,AP-10720,271.9600,5,0.20,27.1960
2355,US-2016-103674,2016-12-06,AP-10720,249.5840,2,0.20,31.1980
2356,US-2016-103674,2016-12-06,AP-10720,437.4720,14,0.20,153.1152
2357,CA-2017-121258,2017-02-26,DB-13060,258.5760,2,0.20,19.3932
2358,CA-2017-119914,2017-05-04,CC-12220,243.1600,2,0.00,72.9480

##### 2. Find the highest sales order for each customer. (Subquery)

In [8]:
query = """
SELECT
`Customer ID`,
MAX(Sales) AS highest_order_value
FROM orders
GROUP BY `Customer ID`
ORDER BY highest_order_value DESC;
"""

pd.read_sql(query, engine)

    Customer ID  highest_order_value
0      SM-20320            22638.480
1      TC-20980            17499.950
2      RB-19360            13999.960
3      TA-21385            11199.968
4      HL-15040            10499.970
..          ...                  ...
788    CJ-11875               16.520
789    MG-18205               12.320
790    RS-19870                9.648
791    LD-16855                5.304
792    TS-21085                2.808

[793 rows x 2 columns]

##### 3. Calculate total sales for each customer. (CTE)

In [9]:
query = """
WITH customer_sales AS
(
SELECT
`Customer ID`,
SUM(Sales) AS total_sales
FROM orders
GROUP BY `Customer ID`
)

SELECT *
FROM customer_sales
ORDER BY total_sales DESC;
"""

pd.read_sql(query, engine)

    Customer ID  total_sales
0      SM-20320    25043.050
1      TC-20980    19052.218
2      RB-19360    15117.339
3      TA-21385    14595.620
4      AB-10105    14473.571
..          ...          ...
788    RS-19870       22.328
789    MG-18205       16.739
790    CJ-11875       16.520
791    LD-16855        5.304
792    TS-21085        4.833

[793 rows x 2 columns]

##### 4. Find customers whose total sales are above average. (CTE + Subquery)

In [10]:
query = """
WITH customer_sales AS
(
SELECT
`Customer ID`,
SUM(Sales) AS total_sales
FROM orders
GROUP BY `Customer ID`
)

SELECT *
FROM customer_sales
WHERE total_sales >
(
SELECT AVG(total_sales)
FROM customer_sales
);
"""

pd.read_sql(query, engine)

    Customer ID  total_sales
0      BH-11710    6255.3510
1      IM-15070    4930.4740
2      PK-19075    8646.9340
3      TB-21520    4737.4860
4      MA-17560    4299.1610
..          ...          ...
289    SB-20185    6410.9960
290    TS-21655    3368.0940
291    VP-21760    3360.5260
292    CM-12715    3984.4524
293    LC-16960    3246.6260

[294 rows x 2 columns]

##### 5. Rank all customers based on total sales. (Window Function)

In [11]:
query = """
WITH customer_sales AS
(
SELECT
`Customer ID`,
SUM(Sales) AS total_sales
FROM orders
GROUP BY `Customer ID`
)

SELECT *,
RANK() OVER(
ORDER BY total_sales DESC
) AS customer_rank
FROM customer_sales;
"""

pd.read_sql(query, engine)

    Customer ID  total_sales  customer_rank
0      SM-20320    25043.050              1
1      TC-20980    19052.218              2
2      RB-19360    15117.339              3
3      TA-21385    14595.620              4
4      AB-10105    14473.571              5
..          ...          ...            ...
788    RS-19870       22.328            789
789    MG-18205       16.739            790
790    CJ-11875       16.520            791
791    LD-16855        5.304            792
792    TS-21085        4.833            793

[793 rows x 3 columns]

##### 6. Assign row numbers to each order within a customer. (Window Function + PARTITION BY)

In [12]:
query = """
SELECT
`Customer ID`,
`Order ID`,
Sales,

ROW_NUMBER() OVER
(
PARTITION BY `Customer ID`
ORDER BY Sales DESC
) AS row_num

FROM orders;
"""

pd.read_sql(query, engine)

     Customer ID        Order ID     Sales  row_num
0       AA-10315  CA-2016-103982  3930.072        1
1       AA-10315  CA-2014-128055   673.568        2
2       AA-10315  CA-2016-103982   431.976        3
3       AA-10315  CA-2017-147039   362.940        4
4       AA-10315  CA-2014-128055    52.980        5
...          ...             ...       ...      ...
9988    ZD-21925  CA-2017-141481    61.440        5
9989    ZD-21925  CA-2014-143336    22.720        6
9990    ZD-21925  US-2016-147991    16.720        7
9991    ZD-21925  CA-2016-152471    15.984        8
9992    ZD-21925  CA-2014-143336     8.560        9

[9993 rows x 4 columns]

##### 7. Display top 3 customers based on total sales. (Window Function)

In [13]:
query = """
WITH customer_sales AS
(
SELECT
`Customer ID`,
SUM(Sales) AS total_sales
FROM orders
GROUP BY `Customer ID`
),

ranked_customers AS
(
SELECT *,
RANK() OVER(
ORDER BY total_sales DESC
) AS customer_rank
FROM customer_sales
)

SELECT *
FROM ranked_customers
WHERE customer_rank <= 3;
"""

pd.read_sql(query, engine)

  Customer ID  total_sales  customer_rank
0    SM-20320    25043.050              1
1    TC-20980    19052.218              2
2    RB-19360    15117.339              3

### Step 3: Final Combined Query

##### Write one final query that shows: 

##### Customer Name  

##### Total Sales  

##### Rank  

##### (Use JOIN + CTE + Window Function together)

In [14]:
query = """
WITH customer_sales AS
(
SELECT
c.`Customer ID`,
c.`Customer Name`,
SUM(o.Sales) AS total_sales

FROM customers c
JOIN orders o
ON c.`Customer ID` = o.`Customer ID`

GROUP BY
c.`Customer ID`,
c.`Customer Name`
)

SELECT *,
RANK() OVER(
ORDER BY total_sales DESC
) AS customer_rank

FROM customer_sales;
"""

pd.read_sql(query, engine)

    Customer ID    Customer Name  total_sales  customer_rank
0      KL-16645     Ken Lonsdale   141752.290              1
1      SE-20110     Sanjit Engle   134303.818              2
2      AB-10105    Adrian Barton   130262.139              3
3      SM-20320      Sean Miller   125215.250              4
4      CL-12565      Clay Ludtke   119686.006              5
..          ...              ...          ...            ...
788    RS-19870       Roy Skaria       44.656            789
789    MG-18205  Mitch Gastineau       16.739            790
790    CJ-11875     Carl Jackson       16.520            791
791    TS-21085    Thais Sissman        9.666            792
792    LD-16855     Lela Donovan        5.304            793

[793 rows x 4 columns]

## Mini Project: Customer Sales Insights

#### Answer the following using SQL:

##### Q1) Who are the top 5 customers?

In [15]:
query = """
SELECT
`Customer ID`,
SUM(Sales) total_sales
FROM orders
GROUP BY `Customer ID`
ORDER BY total_sales DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

  Customer ID  total_sales
0    SM-20320    25043.050
1    TC-20980    19052.218
2    RB-19360    15117.339
3    TA-21385    14595.620
4    AB-10105    14473.571

##### Q2) Who are the bottom 5 customers?

In [16]:
query = """
SELECT
`Customer ID`,
SUM(Sales) total_sales
FROM orders
GROUP BY `Customer ID`
ORDER BY total_sales
LIMIT 5;
"""

pd.read_sql(query, engine)

  Customer ID  total_sales
0    TS-21085        4.833
1    LD-16855        5.304
2    CJ-11875       16.520
3    MG-18205       16.739
4    RS-19870       22.328

##### Q3) Which customers made only one order?

In [17]:
query = """
SELECT
`Customer ID`,
COUNT(DISTINCT `Order ID`) total_orders
FROM orders
GROUP BY `Customer ID`
HAVING COUNT(DISTINCT `Order ID`) = 1;
"""

pd.read_sql(query, engine)

   Customer ID  total_orders
0     AO-10810             1
1     AR-10570             1
2     CJ-11875             1
3     JC-15385             1
4     JR-15700             1
5     LD-16855             1
6     MG-18205             1
7     PH-18790             1
8     RE-19405             1
9     RM-19750             1
10    SM-20905             1
11    TC-21145             1

##### Q4) Which customers have above-average sales?

In [18]:
query = """
SELECT
`Customer ID`,
SUM(Sales) total_sales
FROM orders
GROUP BY `Customer ID`
HAVING SUM(Sales) >
(
SELECT AVG(customer_total)
FROM
(
SELECT SUM(Sales) customer_total
FROM orders
GROUP BY `Customer ID`
) x
);
"""

pd.read_sql(query, engine)

    Customer ID  total_sales
0      BH-11710    6255.3510
1      IM-15070    4930.4740
2      PK-19075    8646.9340
3      TB-21520    4737.4860
4      MA-17560    4299.1610
..          ...          ...
289    SB-20185    6410.9960
290    TS-21655    3368.0940
291    VP-21760    3360.5260
292    CM-12715    3984.4524
293    LC-16960    3246.6260

[294 rows x 2 columns]

##### Q5) What is the highest order value per customer?

In [19]:
query = """
SELECT
`Customer ID`,
MAX(Sales) AS highest_order_value
FROM orders
GROUP BY `Customer ID`
ORDER BY highest_order_value DESC;
"""

pd.read_sql(query, engine)

    Customer ID  highest_order_value
0      SM-20320            22638.480
1      TC-20980            17499.950
2      RB-19360            13999.960
3      TA-21385            11199.968
4      HL-15040            10499.970
..          ...                  ...
788    CJ-11875               16.520
789    MG-18205               12.320
790    RS-19870                9.648
791    LD-16855                5.304
792    TS-21085                2.808

[793 rows x 2 columns]

### Key Insights

#### 1. A small group of customers contributes a significant share of total sales.
#### 2. Top-ranked customers generate substantially higher revenue than the average customer.
#### 3. Several customers placed only one order during the observed period.
#### 4. Customers with sales above the overall average were identified using subqueries and CTEs.
#### 5. Window functions such as ROW_NUMBER() and RANK() simplified customer ranking analysis.
#### 6. Combining JOINs, CTEs, and Window Functions enabled comprehensive customer performance evaluation.